<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NEXGEN - Product Report {{ now()->format('d M Y') }}</title>
    <style>
        @page { margin: 16mm 15mm 14mm 15mm; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; font-size: 12px; color: #222; background: #fff; }

        /* ── SECTION TITLE ── */
        .section-title {
            font-size: 11px; font-weight: 700; color: #1a3a6d;
            text-transform: uppercase; letter-spacing: .5px;
            margin-bottom: 8px; padding-bottom: 4px;
            border-bottom: 2px solid #1a6dd4;
        }

        /* ── TABLE ── */
        .product-table {
            width: 100%; border-collapse: collapse;
            border: 1.5px solid #1a6dd4;
            margin-bottom: 20px;
        }
        .product-table thead tr { background-color: #1a6dd4; }
        .product-table thead th {
            padding: 7px 8px; text-align: center; color: #ffffff;
            font-size: 10px; font-weight: 700;
            border-right: 1px solid #1558b0;
            border-bottom: 1.5px solid #1558b0;
            white-space: nowrap;
        }
        .product-table thead th:last-child { border-right: none; }
        .product-table tbody td {
            padding: 6px 8px; text-align: center;
            border-right: 1px solid #c5d3e8;
            border-bottom: 1px solid #c5d3e8;
            font-size: 10.5px; vertical-align: middle;
        }
        .product-table tbody td:last-child { border-right: none; }
        .product-table tbody tr:last-child td { border-bottom: none; }
        .even-row { background: #f2f6ff; }

        .stock-ok   { color:#065f46; font-weight:700; }
        .stock-low  { color:#92400e; font-weight:700; }
        .stock-zero { color:#991b1b; font-weight:700; }
    </style>
</head>
<body>

{{-- ── LETTERHEAD ── --}}
<table width="100%" border="0" cellpadding="0" cellspacing="0"
       style="border-bottom: 3px solid #1a6dd4; margin-bottom: 20px; padding-bottom: 14px;">
    <tr>
        <td width="72" valign="middle" style="padding-right: 12px;">
            <img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('images/format_logo.png'))) }}"
                 width="72" height="72" alt="NEXGen Logo" style="display:block;">
        </td>
        <td width="4" valign="stretch" style="background:#1a6dd4; opacity:.4;">&nbsp;</td>
        <td valign="middle" style="padding-left: 14px;">
            <div style="font-size:19px; font-weight:800; color:#1a3a6d; letter-spacing:.5px; line-height:1.1;">
                NEXGEN BUILDTECH PVT. LTD.
            </div>
            <div style="font-size:10.5px; color:#444; margin-top:6px; line-height:2;">
                Nepalgunj-18, Banke, Nepal &nbsp;&nbsp;
                +977-9768442449 &nbsp;&nbsp;
                info@nexgenbuildtech.com &nbsp;&nbsp;
                PAN: 62243462
            </div>
        </td>
        <td valign="middle" align="right" style="white-space:nowrap; padding-left:10px;">
            <div style="font-size:13px; font-weight:700; color:#1a6dd4; text-transform:uppercase; letter-spacing:.8px;">
                Product Report
            </div>
            <div style="font-size:10px; color:#555; margin-top:5px; line-height:1.9; text-align:right;">
                Generated: {{ now()->format('d M Y, h:i A') }}<br>
                Total Products: {{ $products->count() }}<br>
                Generated by: Admin
            </div>
        </td>
    </tr>
</table>

{{-- ── SUMMARY CARDS ── --}}
<table width="100%" border="0" cellpadding="0" cellspacing="0"
       style="border-collapse: collapse; margin-bottom: 20px;">
    <tr>
        <td width="25%" align="center"
            style="border:1px solid #ccd6ea; border-radius:6px; padding:10px 12px; background:#f5f8ff;">
            <div style="font-size:17px; font-weight:800; color:#1a3a6d;">{{ $products->count() }}</div>
            <div style="font-size:9px; color:#888; margin-top:2px; text-transform:uppercase; letter-spacing:.4px;">Active Products</div>
        </td>
        <td width="3">&nbsp;</td>
        <td width="25%" align="center"
            style="border:1px solid #ccd6ea; border-radius:6px; padding:10px 12px; background:#f5f8ff;">
            <div style="font-size:17px; font-weight:800; color:#1a3a6d;">Rs {{ number_format($totalStockValue, 0) }}</div>
            <div style="font-size:9px; color:#888; margin-top:2px; text-transform:uppercase; letter-spacing:.4px;">Total Stock Value</div>
        </td>
        <td width="3">&nbsp;</td>
        <td width="25%" align="center"
            style="border:1px solid #ccd6ea; border-radius:6px; padding:10px 12px; background:#f5f8ff;">
            <div style="font-size:17px; font-weight:800; color:#1a3a6d;">Rs {{ number_format($avgPrice, 0) }}</div>
            <div style="font-size:9px; color:#888; margin-top:2px; text-transform:uppercase; letter-spacing:.4px;">Avg Product Price</div>
        </td>
        <td width="3">&nbsp;</td>
        <td width="25%" align="center"
            style="border:1px solid #ccd6ea; border-radius:6px; padding:10px 12px; background:#f5f8ff;">
            <div style="font-size:17px; font-weight:800; color:#1a3a6d;">{{ $products->sum('stock') }}</div>
            <div style="font-size:9px; color:#888; margin-top:2px; text-transform:uppercase; letter-spacing:.4px;">Total Units in Stock</div>
        </td>
    </tr>
</table>

{{-- ── PRODUCT TABLE ── --}}
<div class="section-title">Product Inventory</div>
<table class="product-table">
    <thead>
        <tr>
            <th>S.N.</th>
            <th>Product Name</th>
            <th>Model</th>
            <th>Category</th>
            <th>Price</th>
            <th>Old Price</th>
            <th>Stock</th>
            <th>Added</th>
        </tr>
    </thead>
    <tbody>
        @forelse($products as $i => $product)
        <tr @if($loop->even) class="even-row" @endif>
            <td>{{ $i + 1 }}</td>
            <td style="text-align:left;"><strong>{{ $product->name }}</strong></td>
            <td style="color:#888;">{{ $product->sku ?? '—' }}</td>
            <td>{{ $product->category?->name ?? '—' }}</td>
            <td><strong>Rs {{ number_format($product->price, 0) }}</strong></td>
            <td style="color:#bbb; text-decoration:line-through;">
                {{ $product->old_price ? 'Rs '.number_format($product->old_price, 0) : '—' }}
            </td>
            <td>
                @if($product->stock > 10)
                    <span class="stock-ok">{{ $product->stock }}</span>
                @elseif($product->stock > 0)
                    <span class="stock-low">{{ $product->stock }}</span>
                @else
                    <span class="stock-zero">0</span>
                @endif
            </td>
            <td style="color:#888; white-space:nowrap;">{{ $product->created_at->format('d M Y') }}</td>
        </tr>
        @empty
        <tr>
            <td colspan="8" style="text-align:center; padding:20px; color:#aaa;">No products found.</td>
        </tr>
        @endforelse
    </tbody>
</table>

</body>
</html>
